version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes: 
        - ./data/db:/var/lib/postgresql    
    ports:
      - 5432:5432 
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: cr7
      POSTGRES_DB: ball

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080